"""Add source and source_id to meeting summaries

Revision ID: 8d26776dde4c
Revises: 
Create Date: 2025-07-04 11:40:11.030269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8d26776dde4c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingsummary', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('meetingsummary', sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('meetingsummary', 'drive_file_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_meetingsummary_source'), 'meetingsummary', ['source'], unique=False)
    op.create_index(op.f('ix_meetingsummary_source_id'), 'meetingsummary', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meetingsummary_source_id'), table_name='meetingsummary')
    op.drop_index(op.f('ix_meetingsummary_source'), table_name='meetingsummary')
    op.alter_column('meetingsummary', 'drive_file_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('meetingsummary', 'source_id')
    op.drop_column('meetingsummary', 'source')
    # ### end Alembic commands ###
